### ISSUE TITLE
The tag is missing the first letter v, I can’t refer to the new version in the mod

### ISSUE THREAD

**Issue by acechef** [ramr/go-reaper#19]
![image](https://user-images.githubusercontent.com/13142913/124689549-475f6300-df0b-11eb-802a-529a28d79801.png)

![image](https://user-images.githubusercontent.com/13142913/124689589-5ba36000-df0b-11eb-9ad3-f3f1f757b50d.png)

**Comment by ramr** [comment]
Fixed - there's a tag for the release @ https://github.com/ramr/go-reaper/releases/tag/v0.2.1

Sorry that took a while - for some reason not getting any notifications on this repo.
